jist_dbt:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('DEV_DBT_ENV_SECRET_HOST') }}"
      port: "{{ env_var('DEV_DB_PORT') | as_number }}"
      user: "{{ env_var('DEV_DBT_ENV_SECRET_USER') }}"
      pass: "{{ env_var('DEV_DBT_ENV_SECRET_PASSWORD') }}"
      dbname: "{{ env_var('DEV_DBT_ENV_SECRET_DB') }}"
      schema: "{{ env_var('DEV_DBT_ENV_SECRET_SCHEMA') }}"
    
    stage:
      type: postgres
      threads: 4
      host: "{{ env_var('STAGE_DBT_ENV_SECRET_HOST') }}"
      port: "{{ env_var('STAGE_DB_PORT') | as_number }}"
      user: "{{ env_var('STAGE_DBT_ENV_SECRET_USER') }}"
      pass: "{{ env_var('STAGE_DBT_ENV_SECRET_PASSWORD') }}"
      dbname: "{{ env_var('STAGE_DBT_ENV_SECRET_DB') }}"
      schema: "{{ env_var('STAGE_DBT_ENV_SECRET_SCHEMA') }}"

    production:
      type: postgres
      threads: 4
      host: "{{ env_var('PROD_DBT_ENV_SECRET_HOST') }}"
      port: "{{ env_var('PROD_DB_PORT') | as_number }}"
      user: "{{ env_var('PROD_DBT_ENV_SECRET_USER') }}"
      pass: "{{ env_var('PROD_DBT_ENV_SECRET_PASSWORD') }}"
      dbname: "{{ env_var('PROD_DBT_ENV_SECRET_DB') }}"
      schema: "{{ env_var('PROD_DBT_ENV_SECRET_SCHEMA') }}"

  target: "{{ env_var('DBT_ENV_SECRET_TARGET') }}"
